version: '3.3'
services:
    rdkafka-poc:
        container_name: rdkafka-poc
        build: ./
        volumes:
            - ./:/app
        env_file:
            - .env
        networks:
            - stack
networks: {stack: {}}
